### ISSUE TITLE
Schema Issue

### ISSUE THREAD

**Issue by katiekroik** [jl4282/ModestWear#4]
`error:  { [ValidationError: Clothing validation failed]
  stack: 'Error\n    at MongooseError.ValidationError (/Users/Katie/ModestWear/node_modules/mongoose/lib/error/validation.js:22:16)\n    at model.Document.invalidate (/Users/Katie/ModestWear/node_modules/mongoose/lib/document.js:1260:32)\n    at model.Document.set (/Users/Katie/ModestWear/node_modules/mongoose/lib/document.js:625:10)\n    at model.Document.set (/Users/Katie/ModestWear/node_modules/mongoose/lib/document.js:506:18)\n    at model.Document (/Users/Katie/ModestWear/node_modules/mongoose/lib/document.js:62:10)\n    at model.Model (/Users/Katie/ModestWear/node_modules/mongoose/lib/model.js:45:12)\n    at new model (/Users/Katie/ModestWear/node_modules/mongoose/lib/model.js:2915:11)\n    at Request._callback (/Users/Katie/ModestWear/Scraping/kosherCasual.js:125:7)\n    at Request.self.callback (/Users/Katie/ModestWear/node_modules/request/request.js:198:22)\n    at Request.emit (events.js:98:17)\n    at Request.<anonymous> (/Users/Katie/ModestWear/node_modules/request/request.js:1082:10)\n    at Request.emit (events.js:117:20)\n    at IncomingMessage.<anonymous> (/Users/Katie/ModestWear/node_modules/request/request.js:1009:12)\n    at IncomingMessage.emit (events.js:117:20)\n    at _stream_readable.js:944:16\n    at process._tickCallback (node.js:442:13)',
  message: 'Clothing validation failed',
  name: 'ValidationError',
  errors: 
   { length: 
      { [CastError: Cast to Number failed for value "36-39" at path "length"]
        stack: 'Error\n    at MongooseError.CastError (/Users/Katie/ModestWear/node_modules/mongoose/lib/error/cast.js:18:16)\n    at model.Document.set (/Users/Katie/ModestWear/node_modules/mongoose/lib/document.js:626:7)\n    at model.Document.set (/Users/Katie/ModestWear/node_modules/mongoose/lib/document.js:506:18)\n    at model.Document (/Users/Katie/ModestWear/node_modules/mongoose/lib/document.js:62:10)\n    at model.Model (/Users/Katie/ModestWear/node_modules/mongoose/lib/model.js:45:12)\n    at new model (/Users/Katie/ModestWear/node_modules/mongoose/lib/model.js:2915:11)\n    at Request._callback (/Users/Katie/ModestWear/Scraping/kosherCasual.js:125:7)\n    at Request.self.callback (/Users/Katie/ModestWear/node_modules/request/request.js:198:22)\n    at Request.emit (events.js:98:17)\n    at Request.<anonymous> (/Users/Katie/ModestWear/node_modules/request/request.js:1082:10)\n    at Request.emit (events.js:117:20)\n    at IncomingMessage.<anonymous> (/Users/Katie/ModestWear/node_modules/request/request.js:1009:12)\n    at IncomingMessage.emit (events.js:117:20)\n    at _stream_readable.js:944:16\n    at process._tickCallback (node.js:442:13)',
        message: 'Cast to Number failed for value "36-39" at path "length"',
        name: 'CastError',
        kind: 'Number',
        value: '36-39',
        path: 'length',
        reason: undefined } } }`

**Comment by katiekroik** [comment]
style: Style, defined in Outfit before Style is defined...

**Comment by katiekroik** [comment]
New error : I believe it's failing because it can't find a length that's valued 36-39...

**Comment by jl4282** [comment]
Yes that is an error but it shouldnt be quitting, it should just be for
that one object that it doesnt save.

**Comment by katiekroik** [comment]
Oh interesting. When I'm doing "db.clothings.count()" in another file, it's giving me 0. 
-Never mind...

**Comment by jl4282** [comment]
Did you select the database?
